types:
  - &m5base
      type: select
      target: define
      label: 'M5 Atom light Base'
      values:
        - label: "CAN KIT"
          value: M5_CAN_KIT
          description: "M5 Stack CAN Kit"
          url: "http://docs.m5stack.com/en/atom/atom_can"
        - value: M5_SERIAL_KIT_232
          description: "M5 Stack RS232 Base"
          label: "Atomic RS232 Base"
          url: "http://docs.m5stack.com/en/atom/Atomic%20RS232%20Base"
        - value: M5_SERIAL_KIT_485
          description: "M5 Stack RS484 Base"
          label: "Atomic RS485 Base"
          url: "http://docs.m5stack.com/en/atom/Atomic%20RS485%20Base"
  - &m5groove
    type: select
    label: 'M5 groove type'
    values:
      - label: 'CAN'
        children: 
      - label: 'I2C'
        children:
        - *m5groovei2c
      - label: 'Serial'
        children:
        - *m5grooveserial
  
  - &m5groovei2c
    type: multi
    label: "M5 I2C groove units"
    values:
      
  - &m5grooveserial
    type: select
    label: "M5 Serial Unit"
    target: define
    values:
      - label: "RS485"
        value: SERIAL_GROOVE_485
        description: "M5 RS485 unit"
        url: "http://docs.m5stack.com/en/unit/rs485"
      - label: "Tail485"
        value: SERIAL_GROOVE_485
        description: "M5 Tail 485"
        url: "http://docs.m5stack.com/en/atom/tail485"

config:
  board:
    type: select
    target: environment
    label: 'Board'
    values: 
      - value: m5stack-atom-generic
        label: m5stack-atom
        description: "M5 Stack Atom light"
        url: "http://docs.m5stack.com/en/core/atom_lite"
        children:
          - *m5base
          - *m5groove